@startuml

'class abstraite
abstract class User {
  +id: bigint
  +firstName: string
  +lastName: string
  +email: string
  +password: string
}

' heritage 

class Admin {
  - role:string
}

class Responsable {
  - role:string
}

class Membre {
  - role:string
}

User <|-- Admin
User <|-- Responsable
User <|-- Membre

' les class

class Annonce {
  +id: bigint
  +titre: string
  +contenu: text
  +type: string
}

class Demande {
  +id: bigint
  +type: string
  +description: text
  +status: string
  +date: date
}

class Tache {
  +id: bigint
  +titre: string
  +description: text
  +status: string
  +dateLimite: datetime
}

class Reunion {
  +id: bigint
  +titre: string
  +description: text
  +date: date
  +heure: time
  +lieu: string
}

class Commentaire {
  +id: bigint
  +contenu: text
  +createdAt: datetime
  +user_id:bigint
  +commentable_id: bigint
  +commentable_type: string
}

class Notification {
  +id: bigint
  +message: string
  +lu: boolean
  +notificable_id: bigint
  +notificable_type:bigint
}

'tableau piveau

class Affectation {
  +status: string
}

class Invitation {
  +status: string
}

' user relations

User "1" -- "0..*" Annonce 
User "1" -- "0..*" Tache : crée
User "1" -- "0..*" Reunion : organise
Admin "1" -- "0..*" Commentaire : écrit
Responsable "1" -- "0..*" Commentaire : écrit

Membre "1" -- "0..*" Demande : crée
Responsable "1" -- "0..*" Demande : traiter
Admin "1" -- "0..*" Demande : traiter

' many to many

User "1" -- "0..*" Affectation
Tache "1" -- "0..*" Affectation

User "1" -- "0..*" Invitation
Reunion "1" -- "0..*" Invitation

'la composition

Annonce "1" *-- "0..*" Commentaire
Tache "1" *-- "0..*" Commentaire
Reunion "1" *-- "0..*" Commentaire
Tache "1" *-- "0..*" Notification
Reunion "1" *-- "0..*" Notification
Annonce "1" *-- "0..*" Notification


' agregation

User "1" o-- "0..*" Notification

@enduml