@startuml TeamBoard
left to right direction

actor Visiteur
actor Admin
actor Membre
actor Responsable

rectangle TeamBoard {

    ' Authentification
    usecase "Se connecter" as Login
    usecase "Se déconnecter" as Logout

    ' Membre
    usecase "Consulter les nouveautés" as News
    usecase "Soumettre une demande" as Ask
    usecase "Consulter les réunions" as ViewMeetings

    ' Responsable
    usecase "Traiter les demandes" as ManageAsk
    usecase "Accepter la demande" as AcceptAsk
    usecase "Refuser la demande" as RefuseAsk
    usecase "Gérer les nouveautés" as ManageNews
    usecase "Gérer les notifications" as ManageNotice
    usecase "Gérer les employés" as ManageAccounts

    ' Réunions
    usecase "Planifier une réunion" as PlanMeeting
    usecase "Modifier une réunion" as EditMeeting
    usecase "Supprimer une réunion" as DeleteMeeting
    usecase "Consulter les réunions (Responsable)" as ViewMeetingsResp

    ' Admin
    usecase "Gérer les comptes des responsables" as gestion_responsables
    usecase "Gérer les nouveautés" as gestion_nouveautes
    usecase "Gérer les comptes des membres" as gestion_membres
    usecase "Gérer les comptes des administrateurs" as gestion_admins
}

'--------- Visiteur -----------
Visiteur --> Login 

' -------- Relations Membre --------
Membre --> Login
Membre --> Logout
Membre --> News
Membre --> Ask
Membre --> ViewMeetings

News ..> Login : <<include>>
Ask ..> Login : <<include>>
ViewMeetings ..> Login : <<include>>

' -------- Relations Responsable --------
Responsable --> Logout
Responsable --> ManageAsk
Responsable --> ManageNews
Responsable --> ManageNotice
Responsable --> ManageAccounts

Responsable --> PlanMeeting
Responsable --> ViewMeetingsResp

ManageAsk ..> Login : <<include>>
ManageNews ..> Login : <<include>>
ManageNotice ..> Login : <<include>>
ManageAccounts ..> Login : <<include>>

PlanMeeting ..> Login : <<include>>
ViewMeetingsResp ..> Login : <<include>>

PlanMeeting ..> EditMeeting : <<extend>>
PlanMeeting ..> DeleteMeeting : <<extend>>

ManageAsk ..> AcceptAsk : <<extend>>
ManageAsk ..> RefuseAsk : <<extend>>

' -------- Relations Admin --------
Admin --> Logout
Admin --> gestion_admins
Admin --> gestion_membres
Admin --> gestion_responsables
Admin --> gestion_nouveautes

gestion_admins ..> Login : <<include>>
gestion_membres ..> Login : <<include>>
gestion_responsables ..> Login : <<include>>
gestion_nouveautes ..> Login : <<include>>

@enduml